name = "YYZRegistry"
uuid = "9912f57a-6282-41c4-b670-b403d7914e01"
repo = "https://github.com/yiyuezhuo/YYZRegistry.git"

[packages]
456b9c66-a11c-41ca-89fd-0ec2d9172aac = { name = "CoralTools", path = "C/CoralTools" }
4fa75a25-d952-42fa-ab2f-cd6b34c94ec2 = { name = "YPPL_Inference", path = "Y/YPPL_Inference" }
52cbd3d6-767d-4c35-a6ca-8d7d1225d4b0 = { name = "EFDCLGT_LR_Files", path = "E/EFDCLGT_LR_Files" }
54e4aa61-68be-4ac6-9fad-ed7868cad30c = { name = "YPPL_Parser", path = "Y/YPPL_Parser" }
6aaf26a4-c633-11e8-35ae-8904cb805353 = { name = "Geodesics", path = "G/Geodesics" }
8586373c-c82d-4ad1-8f52-73ab153c2be0 = { name = "EFDCLGT_LR_Runner", path = "E/EFDCLGT_LR_Runner" }
889110da-db61-40bf-983e-4fb6a8ea23c7 = { name = "CoralData", path = "C/CoralData" }
a726fbc3-c738-4ce7-b537-27edbf17c83f = { name = "PhysicalVectorsData", path = "P/PhysicalVectorsData" }
d2242d40-5c46-404c-a207-f3d6a3667631 = { name = "CoralSetup", path = "C/CoralSetup" }
ece10b52-bc5d-5f9f-8b6e-cc9c6a4b5293 = { name = "KissThreading", path = "K/KissThreading" }
f7755522-bb72-47e4-a4f1-ac7cf6a9e10b = { name = "YPPL_Diagnosis", path = "Y/YPPL_Diagnosis" }
